In [2]:
# Mounting with google drive
from google.colab import drive 
drive.mount("/content/myDrive")

Drive already mounted at /content/myDrive; to attempt to forcibly remount, call drive.mount("/content/myDrive", force_remount=True).


## **Theory :: Reinforcement Learning**


<img src="/content/myDrive/MyDrive/ReinforcementLearning/yt-course-deeplizard/note1.png">
<br>
<img src="/content/myDrive/MyDrive/ReinforcementLearning/yt-course-deeplizard/note2.png">
<br>
<img src="/content/myDrive/MyDrive/ReinforcementLearning/yt-course-deeplizard/note3.png">
<br>


## Q-Learning Frozen lake 

#### Installs and import 

In [ ]:
!pip install numpy gym ipython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# import packeges \'\\''\''\''\\'\'\''\'\'\\\'\'\''\'\\\'\
import numpy as np
import gym 
import random
import time 
from IPython.display import clear_output 


In [ ]:
#%%  Creating gym environment 
env=gym.make("FrozenLake-v0")

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n 
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Declearing  Global Variable for **QLearning Algorithm**

In [ ]:
num_episodes=10_000
max_steps_per_episode=10

learning_rate = 0.1
discount_rate = 0.99 

exploration_rate = 1 # Initial 
max_exploration_rate = 1
min_exploration_rate = 0.01 
exploration_decay_rate = 0.001


#### Q-Learning Algorithm


In [ ]:
rewards_all_episodes = []
# Q-Learning Algorithm Begine 
for episode in range(num_episodes):
  state=env.reset()

  is_done = False 
  rewards_current_episode = 0

  for step in range(max_steps_per_episode):
    # Exploration-Exploitation trade of 
    exploration_rate_thresold = random.uniform(0,1)
    if exploration_rate_thresold>exploration_rate:
      action=np.argmax(q_table[state,:])
    else : 
      action = env.action_space.sample()
    new_state, reward, is_done, info = env.step(action)

    # Updating Q-table for Q(s,a)
    q_table[state, action]= q_table[state, action]*(1-learning_rate)+ \
        learning_rate*(reward+discount_rate*np.max(q_table[new_state,:])) 
    state=new_state
    rewards_current_episode+=reward
    if is_done:
       break
  
  exploration_rate = min_exploration_rate = + \
      (max_exploration_rate-min_exploration_rate)*\
        np.exp(-exploration_decay_rate*episode)

  rewards_all_episodes.append(rewards_current_episode)

reward_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("******Avarage reward per thousand episode******\n")
for r in reward_per_thousand_episodes:
  print('\t',count,': ',sum(r/1000))
  count+=1000
print("\n******Q-Table*******\n")
print(q_table)

******Avarage reward per thousand episode******

	 1000 :  0.0
	 2000 :  0.0
	 3000 :  0.0
	 4000 :  0.0
	 5000 :  0.0
	 6000 :  0.0
	 7000 :  0.0
	 8000 :  0.0
	 9000 :  0.0
	 10000 :  0.0

******Q-Table*******

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
